# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69dc7598dc505f4814e8ee14a83b6b7a48c3512c51c3e16fe91ba986b5313f519d3d860030e72f18e183851b2cb184306bf8a92dafdc26fffb72c2521d3d7b76

test:
  secret_key_base: 8d742d7cd2b722fbba322f352637ccb21dd862fa9da7d9f8ed233507076e363452bd9130fa0482d3516700926ea86457958c9aaef5334eb2a47f273ca7a17156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
